// Which language a transcript or a sentence is in, so the reply is spoken by that language's voice
// (spec 003). Parakeet doesn't say which language it heard, and a model for this would be one more
// download; common words are enough to tell these apart. Unsure (a short "OK."), it says nothing and
// the caller keeps the language it had.
const COMMON_WORDS: Record<string, string[]> = {
  en: [
    "the",
    "and",
    "is",
    "are",
    "you",
    "to",
    "of",
    "it",
    "that",
    "what",
    "this",
    "for",
    "with",
    "have",
    "i",
    "my",
    "your",
    "do",
    "can",
    "on",
    "in",
    "be",
    "was",
    "will",
    "not",
    "me",
    "please",
    "tomorrow",
    "today",
  ],
  it: [
    "il",
    "lo",
    "la",
    "gli",
    "le",
    "di",
    "che",
    "è",
    "e",
    "un",
    "una",
    "per",
    "con",
    "non",
    "sono",
    "mi",
    "ti",
    "ho",
    "hai",
    "cosa",
    "come",
    "del",
    "della",
    "dei",
    "delle",
    "nel",
    "nella",
    "fai",
    "oggi",
    "domani",
    "anche",
    "questo",
    "quello",
    "sì",
    "grazie",
  ],
  es: [
    "el",
    "los",
    "las",
    "de",
    "que",
    "es",
    "y",
    "un",
    "una",
    "por",
    "con",
    "no",
    "para",
    "lo",
    "mi",
    "tu",
    "qué",
    "cómo",
    "está",
    "son",
    "hoy",
    "mañana",
    "gracias",
    "pero",
    "muy",
    "también",
  ],
  fr: [
    "le",
    "les",
    "des",
    "de",
    "et",
    "est",
    "un",
    "une",
    "pour",
    "avec",
    "pas",
    "je",
    "tu",
    "vous",
    "nous",
    "que",
    "qui",
    "ce",
    "cette",
    "dans",
    "sur",
    "aujourd'hui",
    "demain",
    "merci",
    "oui",
    "mais",
    "très",
  ],
  de: [
    "der",
    "die",
    "das",
    "und",
    "ist",
    "ein",
    "eine",
    "nicht",
    "ich",
    "du",
    "sie",
    "wir",
    "mit",
    "für",
    "auf",
    "zu",
    "den",
    "dem",
    "was",
    "wie",
    "heute",
    "morgen",
    "danke",
    "ja",
    "auch",
    "bitte",
  ],
  pt: [
    "o",
    "os",
    "as",
    "de",
    "que",
    "é",
    "e",
    "um",
    "uma",
    "para",
    "com",
    "não",
    "eu",
    "você",
    "do",
    "da",
    "dos",
    "das",
    "no",
    "na",
    "hoje",
    "amanhã",
    "obrigado",
    "obrigada",
    "sim",
    "também",
    "muito",
  ],
};
const LANGUAGES = Object.keys(COMMON_WORDS);
const WORDS = new Map(
  LANGUAGES.map((language) => [language, new Set(COMMON_WORDS[language])])
);

function guessLanguage(
  text: string,
  among: readonly string[] = LANGUAGES
): string | undefined {
  // "dell'agente" counts as "dell'" and "agente"; "aujourd'hui" stays one word.
  const words = text.toLowerCase().match(/[\p{L}]+(?:'(?:hui))?/gu) ?? [];
  const scores = among
    .map((language) => ({
      language,
      score: words.filter((word) => WORDS.get(language)?.has(word)).length,
    }))
    .sort((a, b) => b.score - a.score);
  const [best, second] = scores;
  if (!best || best.score < 2) return undefined;
  return best.score > (second?.score ?? 0) ? best.language : undefined;
}

export { LANGUAGES, guessLanguage };
