import { describe, expect, it } from "vitest";

import { buildFacesHeader } from "./build-faces-header";
import { facesData } from "./faces-data";

const header = buildFacesHeader(facesData);

describe("buildFacesHeader", () => {
  it("says it is generated and must not be edited", () => {
    expect(header).toMatch(
      /^\/\/ Generated by packages\/design\/scripts\/export-faces\.ts/
    );
  });

  it("lists every face with its glyphs, escaped for C++", () => {
    expect(header).toContain('{"neutral", "o", "o", nullptr,');
    expect(header).toContain('{"joy", "^", "^", "v",');
    // Face lines carry at least three strings; state and colour lines carry fewer.
    expect(header.match(/^\s+\{"[a-z_]+", "[^"]*", "[^"]*", /gm)?.length).toBe(
      facesData.faces.length
    );
  });

  it("keeps the needs-you orange and every agent state", () => {
    expect(header).toContain("kSignal = 0xFF5A1F;");
    for (const state of facesData.states)
      expect(header).toContain(`{"${state.id}", "${state.face}"}`);
  });

  it("drops the emoji-blocking variation selector the firmware doesn't need", () => {
    expect(header).not.toContain("︎");
  });
});
