import type { FacesData } from "./types";

const VARIATION_SELECTOR = /︎/g;

function cString(value: string | undefined): string {
  if (value === undefined) return "nullptr";
  return JSON.stringify(value.replace(VARIATION_SELECTOR, ""));
}

function num(value: number | undefined, fallback: number): string {
  const n = value ?? fallback;
  return Number.isInteger(n) ? `${n}.0f` : `${n}f`;
}

function hex(value: string): string {
  return `0x${value.slice(1).toUpperCase()}`;
}

// The firmware draws the same faces as the browser engine; generating them keeps the two identical.
function buildFacesHeader(data: FacesData): string {
  const faces = data.faces
    .map(
      (f) =>
        `    {${cString(f.id)}, ${cString(f.L)}, ${cString(f.R)}, ${cString(f.M)}, ${num(f.gx, 0)}, ${num(f.gy, 0)}, ${num(f.dy, 0)}, ${num(f.dl, 0)}, ${num(f.dr, 0)}, ${num(f.rl, 0)}, ${num(f.rr, 0)}, ${num(f.sl, 1)}, ${num(f.sr, 1)}, ${num(f.tilt, 0)}, ${cString(f.fx)}},`
    )
    .join("\n");
  const states = data.states
    .map((s) => `    {${cString(s.id)}, ${cString(s.face)}},`)
    .join("\n");
  const colours = data.colours
    .map(
      (c) => `    {${cString(c.id)}, ${hex(c.c)}, ${hex(c.g)}, ${hex(c.key)}},`
    )
    .join("\n");
  return `// Generated by packages/design/scripts/export-faces.ts from packages/design/faces.json. Do not edit.
#pragma once

#include <cstdint>

namespace charm::design {

// Offsets are fractions of the screen's short side, rotations in degrees, scales multipliers.
struct Face {
  const char* id;
  const char* left;
  const char* right;
  const char* mouth;
  float gx, gy, dy, dl, dr, rl, rr, sl, sr, tilt;
  const char* fx;
};

struct State {
  const char* id;
  const char* face;
};

struct Colour {
  const char* id;
  uint32_t shell, glyph, key;
};

inline constexpr uint32_t kSignal = ${hex(data.signal)};

inline constexpr Face kFaces[] = {
${faces}
};

inline constexpr State kStates[] = {
${states}
};

inline constexpr Colour kColours[] = {
${colours}
};

}  // namespace charm::design
`;
}

export { buildFacesHeader };
