import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_PATH = join(HERE, "prototype-template.html");
const PROTOTYPE_PATH = join(HERE, "PROTOTYPE.html");
const VIEW_DIR = join(HERE, "..", "stl", "view");
const MARKER = "<!--STL_DATA-->";
const PARTS = ["front", "back", "key"] as const;

// The STLs are embedded as base64 so the 3D view works when the page is opened straight from disk (file://).
function buildPrototypeHtml(): string {
  const template = readFileSync(TEMPLATE_PATH, "utf8");
  if (!template.includes(MARKER)) {
    throw new Error(`prototype-template.html is missing ${MARKER}`);
  }
  const blocks = PARTS.map((part) => {
    const base64 = readFileSync(join(VIEW_DIR, `view_${part}.stl`)).toString(
      "base64"
    );
    return `<script type="text/plain" id="stl-${part}">${base64}</script>`;
  });
  return template.replace(
    MARKER,
    `<!-- generated by hardware/prototype/build-prototype.ts: assembly STL data -->\n${blocks.join("\n")}`
  );
}

function writePrototype(): void {
  const html = buildPrototypeHtml();
  writeFileSync(PROTOTYPE_PATH, html);
  console.log(
    `wrote hardware/prototype/PROTOTYPE.html ${Math.round(html.length / 1024)} KB`
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) writePrototype();

export { PROTOTYPE_PATH, buildPrototypeHtml };
